#!/bin/bash
#!/bin/sh
#
#Sisseehitatud tsüklid
#
SALASONA="qwerty"
echo -n "Sisesta salasõna: "
read SALASONA1

if [ "$SALASONA1" == "$SALASONA" ]
then
	echo "Ligipääs lubatud!"
	for (( i = 1; i <= 5; i++ ))
	do
		for (( j = 1; j <= 5; j++ ))
		do
			echo -n "$i "
		done
		echo
	done
else
	echo "Ligipääs keelatud!"
fi
