#!/bin/bash
#
#10 esimese arvu summa - liida ainult paaris arvud
#
summa=0
for (( arv=1; arv<=10; arv++ ))
do
	jaak=$(($arv % 2))
	if [ $jaak -eq 0  ]; then
		summa=$(($summa + $arv))
		echo $summa
	fi
done
#skripti lõpp
