#!/bin/bash
#
#10 esimese arvu summa - liida ainult paaris arvud
#
echo -n "Sisesta suvaline täisarv: "
read arv1
kriips=""
aarv=$arv1
while [ $arv1 -eq 0 ]; do
	echo -n "Sisesta palun teine täisarv: "
	read arv1
done
if [ $arv1 -lt 0 ]; then
	arv1=$(($arv1 * -1))
	kriips="-"
fi
summa=0
while [ $arv1 -gt 0  ]
do
	jaak=$(($arv1 % 10))
	summa=$(($summa + $jaak))
	arv1=$(($arv1 / 10))
done
echo "Arvu $aarv numbrite summa on: $kriips$summa"
#skripti lõpp
