#!/bin/bash
#
#Keskkonna ja oma muutujate kasutamine.
#
#Kasutame keskonna muutuja nimega $USER
#tervitame kasutajat
echo "Tere, $USER!"
#kuupäeva väärtuse loomine
#defineerime vastava väärtusega muutuja
kuupaev=`date +'%d. %B'`
#väljastame kuupäeva koos seletusega
echo "Täna on $kuupaev"
