#!/bin/bash
#
#Arvu kontroll - positiivne või negatiivne
#
#kontrollime, kas on sisestatud üks parameeter
if [ $# -ne 1 ];then
echo "Kasutusjuhend:"
echo "$0 arv"
echo "Näiteks: $0 5"
#Kui on kõik korras, ja parameetrite arv 1
else
arv=$1
#nüüd kontrollime, kas arv on positiivne
#sel juhul peab arv olema suurem kui 0
if [ $arv -gt 0 ]; then
#jah, arv on suurem, kui 0 - positiivne
echo "$arv on positiivne"
#kui ei ole suurem, kui 0 - negatiivne
elif [ $arv -lt 0 ]; then
echo "$arv on negatiivne"
else
echo "$arv on neutraalne"
fi
fi
