#!/bin/bash
#
#Arvu kontroll - positiivne või negatiivne
#
echo -n "Sisesta arv:"
read arv
#nüüd kontrollime, kas arv on positiivne
#sel juhul peab arv olema suurem kui 0
if [ $arv -gt 0 ]
then
#jah, arv on suurem, kui 0 - positiivne
echo "$arv on positiivne"
#kui ei ole suurem, kui 0 - negatiivne
else
echo "$arv on negatiivne"
fi
